### ISSUE TITLE
"gethexaformat" messes up column widths

### ISSUE THREAD

**Issue by cpacejo** [gui-cs/NStack#86]
[This patch](https://github.com/gui-cs/NStack/commit/ece66dd1c7c6a62610f20b41dc7fcc7c0ea00114) and [this patch](https://github.com/gui-cs/NStack/commit/e684110bc6eec1980db169a2ce9a63443c36c559) seem to have messed up column widths.  E.g. the Unicode character "𝔹" (U+1D539) is counted as double-width.  Before these patches, it did not fall in any of the double-width ranges.  However, after these patches, `gethexaformat` conflates U+1D539 with U+D539 (픹), which is considered as a wide character.

I don't understand what the purpose of `gethexaformat` is -- it seems to just be performing the bitwise operation `x & 0xFFFF`, but using text parsing?  Why are only the least significant 16 bits considered when determining whether a character is wide?  This seems like it would cause many characters beside my example to have the wrong width...

**Comment by tig** [comment]
@BDisp - Please review
